version: "3.8"

services:
  web:
    container_name: web
    stdin_open: true
    tty: true
    command: npm run dev
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    env_file: .env
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 40s
      retries: 4

volumes:
  postgres_data:
